name: built_union_test
author: real <real@freedomlayer.org>
version: 0.1.0

environment:
    sdk: '>=2.6.0 <3.0.0'

dependencies:
    meta: ^1.1.0
    built_value: ^7.0.6
    built_union: ^0.1.0
    built_collection: '>=2.0.0 <5.0.0'
    test: ^1.0.0

dev_dependencies:
    built_value_generator: ^7.0.8
    built_union_generator: ^0.1.0
    build_runner: ^1.0.0

dependency_overrides:
    built_union:
        path: ../built_union
    built_union_generator:
        path: ../built_union_generator
