name: built_union_test
version: 0.1.2
description: >
  Dart sum-types, compatible with built_value.dart
  This library contains integration tests for built_union.dart
homepage: https://github.com/freedomlayer/built_union.dart

environment:
    sdk: '>=2.6.0 <3.0.0'

dependencies:
    meta: ^1.1.0
    built_value: ^7.0.6
    built_union: ^0.1.0
    built_collection: '>=2.0.0 <5.0.0'
    test: ^1.0.0

dev_dependencies:
    built_value_generator: ^7.0.8
    built_union_generator: ^0.1.0
    build_runner: ^1.0.0

