name: built_union_generator
author: real <real@freedomlayer.org>
version: 0.1.0

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  build: ^1.1.0
  built_collection: '>=2.0.0 <5.0.0'
  built_union: ^0.1.0

dev_dependencies:
  built_value_generator: ^7.0.6
  build_test: ^0.10.3
  test: ^1.0.0

