name: built_union_generator
version: 0.1.1
description: >
  Dart sum-types, compatible with built_value.dart
  This library is the dev dependency.
homepage: https://github.com/freedomlayer/built_union.dart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  build: ^1.1.0
  built_collection: '>=2.0.0 <5.0.0'
  built_union: ^0.1.0
  analyzer: '>=0.39.3 <0.40.0'
  source_gen: ^0.9.0
  meta: ^1.1.0

dev_dependencies:
  built_value_generator: ^7.0.6
  build_test: ^0.10.3
  logging: ^0.11.0
  test: ^1.0.0

