name: built_union
version: 0.1.0
description: >
  Dart sum-types, compatible with built_value.dart
  This library is the runtime dependency.
homepage: https://github.com/freedomlayer/built_union.dart

environment:
    sdk: '>=2.6.0 <3.0.0'

dependencies:
    meta: ^1.1.0
    built_value: ^7.0.6
    built_collection: '>=2.0.0 <5.0.0'

dev_dependencies:
    test: ^1.0.0
